amap:
  base_url: https://restapi.amap.com/v3/assistant/coordinate/convert?key=1b1d683b4c20b3a09c3b2045cb719253&locations=
upload_path:
  fire: D:/Research/Sanitation/assessment/result/polygons/fire/
  san: D:/Research/Sanitation/assessment/result/polygons/san/

directories:
  buildings_dir:  D:/Research/Sanitation/assessment/data/data_for_test/buildings  # 建筑数据所在目录
  temp_file:  D:/Research/Sanitation/assessment/data/temp/valuation  # 现状评估时的临时文件夹
  temp_file_planning:  D:/Research/Sanitation/assessment/data/temp/planning  # 用地规划时的临时文件夹
  result_file:  D:/Research/Sanitation/assessment/result  # 结果存放文件夹
shp_path:
  polygons:  D:/Research/Sanitation/assessment/data/data_for_test/polygons/test.shp  # 地块数据
  fire_path: D:/Research/Sanitation/assessment/code_s/portal/data/
  san_path: D:/Research/Sanitation/assessment/code_s/portal/data/
  fire_shp: D:/Research/Sanitation/assessment/result/polygons/target.shp
  san_shp: D:/Research/Sanitation/assessment/result/polygons/target.shp
  #roads: C:/Users/Administrator/Desktop/assessment/data/data_for_test/roads/roads_cut_topo_ND.nd  # 路网数据
  hazardous_facilities:  D:/Research/Sanitation/assessment/data/data_for_test/POIs/hazardous_facilities.shp  # 危险设施POI
  polygons_for_planning:  D:/Research/Sanitation/assessment/data/data_for_test/polygons/planning.shp  # 用于规划的用地数据
excel_path:
  per_capita_service_area:  D:/Research/Sanitation/assessment/data/data_for_test/tables/per_capita_service_area.xlsx  # 人均服务面积表
  N_extent:  D:/Research/Sanitation/assessment/data/data_for_test/tables/N_extent.xlsx  # N计算范围
  fire_risk_weights:  D:/Research/Sanitation/assessment/data/data_for_test/tables/fire_risk_weights.xlsx  # 用地消防风险系数表
  fire_path: D:/Research/Sanitation/assessment/code_s/data/fire_fightings.xlsx  # 消防站、环卫站数据存放的目录
  san_path: D:/Research/Sanitation/assessment/code_s/data/sanitations.xlsx  # 消防站、环卫站数据存放的目录
buffers:
  fire_buffers: [500.0, 1000.0, 1500.0, 2000.0, 2500.0]  # 计算消防站可达性S的多级缓冲区的缓冲半径（米）
  collection_buffers: [500.0, 1000.0, 1500.0, 2000.0]  # 计算垃圾收集站可达性S的多级缓冲区的缓冲半径（米）
  transfer_buffers: [2000.0, 4000.0, 6000.0, 8000.0, 10000.0]  # 计算垃圾转运站可达性S的多级缓冲区的缓冲半径（米）
  hazard_buffers: [10.0, 50.0, 100.0, 200.0, 500.0]  # 计算消防危险设施N3的多级缓冲区的缓冲半径（米）
parameters:
  C: 1.1  # 预测的平均日人均生活垃圾产量[kg/(人·d)]，可取0.8kg/(人·d) ~ 1.4kg/(人·d)
  A: 1.3  # 生活垃圾日产量不均匀系数，可取1 ~ 1.5
other_files:
  pop_raster:  D:/Research/Sanitation/assessment/data/data_for_test/pop/hubei_pop.tif  # 人口密度栅格